package com.fullmetalsonic.vehiclenote;
import android.app.*;
import android.content.*;
import android.os.Build;
import androidx.core.app.NotificationCompat;
import androidx.core.app.NotificationManagerCompat;
import org.json.*;
import java.util.*;
import java.text.SimpleDateFormat;
public class ReminderReceiver extends BroadcastReceiver {
    private static final String CHANNEL="vehicle-maintenance";
    static PendingIntent alarmIntent(Context c){return PendingIntent.getBroadcast(c,701,new Intent(c,ReminderReceiver.class).setAction("VEHICLE_DAILY"),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);}
    static void schedule(Context c){try{AlarmManager am=(AlarmManager)c.getSystemService(Context.ALARM_SERVICE);am.cancel(alarmIntent(c));JSONObject plan=new JSONObject(c.getSharedPreferences("vehicle-notifications",0).getString("plan","{}"));if(!plan.optBoolean("enabled"))return;Calendar next=Calendar.getInstance(TimeZone.getTimeZone("Asia/Seoul"));next.set(Calendar.HOUR_OF_DAY,9);next.set(Calendar.MINUTE,0);next.set(Calendar.SECOND,0);next.set(Calendar.MILLISECOND,0);if(next.getTimeInMillis()<=System.currentTimeMillis())next.add(Calendar.DAY_OF_MONTH,1);am.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,next.getTimeInMillis(),alarmIntent(c));}catch(Exception e){throw new IllegalStateException("Reminder scheduling failed",e);}}
    static void post(Context c,String title,String body){NotificationManager nm=(NotificationManager)c.getSystemService(Context.NOTIFICATION_SERVICE);if(Build.VERSION.SDK_INT>=26)nm.createNotificationChannel(new NotificationChannel(CHANNEL,"차량 정비 예정",NotificationManager.IMPORTANCE_DEFAULT));PendingIntent open=PendingIntent.getActivity(c,702,new Intent(c,MainActivity.class).setFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);NotificationCompat.Builder b=new NotificationCompat.Builder(c,CHANNEL).setSmallIcon(android.R.drawable.ic_dialog_info).setContentTitle(title).setContentText(body).setContentIntent(open).setAutoCancel(true).setVisibility(NotificationCompat.VISIBILITY_PRIVATE);nm.notify(703,b.build());}
    @Override public void onReceive(Context c,Intent intent){try{if(!"VEHICLE_DAILY".equals(intent.getAction())){schedule(c);return;}SharedPreferences prefs=c.getSharedPreferences("vehicle-notifications",0);JSONObject plan=new JSONObject(prefs.getString("plan","{}"));if(!plan.optBoolean("enabled"))return;SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd",Locale.ROOT);format.setTimeZone(TimeZone.getTimeZone("Asia/Seoul"));String today=format.format(new Date());Set<String> seen=new HashSet<>(prefs.getStringSet("seen",Collections.emptySet())),activeKeys=new HashSet<>(),send=new HashSet<>();JSONArray rows=plan.optJSONArray("entries");if(rows!=null)for(int i=0;i<rows.length();i++){JSONObject row=rows.getJSONObject(i);String key=row.getString("key");activeKeys.add(key);if(today.compareTo(row.getString("start"))>=0&&today.compareTo(row.getString("end"))<=0&&!seen.contains(key))send.add(key);}String expiry=plan.optString("expiresAt","");if(!expiry.isEmpty()&&today.compareTo(expiry)>0){String refresh="refresh|"+expiry;activeKeys.add(refresh);if(!seen.contains(refresh)&&NotificationManagerCompat.from(c).areNotificationsEnabled()){post(c,"정비 알림 갱신 필요","차량 노트를 열어 주행거리와 알림 계획을 갱신해 주세요.");seen.add(refresh);}}seen.retainAll(activeKeys);if(!send.isEmpty()&&NotificationManagerCompat.from(c).areNotificationsEnabled()){post(c,"차량 정비 예정", "확인할 정비 항목 "+send.size()+"건이 있습니다. 앱에서 확인하세요.");seen.addAll(send);}prefs.edit().putStringSet("seen",seen).apply();}catch(Exception ignored){}finally{try{schedule(c);}catch(Exception ignored){}}}
}
