// Generated public research projection; no owner data is read.
const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),read=n=>JSON.parse(fs.readFileSync(path.join(root,'data',n),'utf8'));
const defaults=read('launch-defaults.json'),profiles=read('management-profiles.json');
const appVersion=fs.readFileSync(path.join(root,'android/app/build.gradle'),'utf8').match(/versionName "([^"]+)"/)[1];
fs.writeFileSync(path.join(root,'ui/app-version.js'),'// Generated from Android versionName.\nexport const appVersion='+JSON.stringify(appVersion)+';\n');
const rows=defaults.rows.map(r=>({id:r.component_id,name:r.name,pack:{PK1:'basic',PK2:'major',PK3:'long',PK4:'body'}[profiles.items.find(p=>p.id===r.component_id).primary_pack],system:r.system,applicability:profiles.items.find(p=>p.id===r.component_id).applicability_text,mode:r.mode,action:r.default_action,proposedKm:r.interval_km,proposedMonths:r.interval_months,criteria:r.criteria,sources:r.source_ids,caseIds:r.implementation_case_ids,scopeGuard:r.scope_guard}));
if(rows.length!==223||new Set(rows.map(r=>r.id)).size!==223)throw Error('Catalog identity mismatch');
fs.writeFileSync(path.join(root,'ui','catalog-data.js'),'// Generated by scripts/build-catalog.cjs from approved research.\nexport const catalogVersion='+JSON.stringify(defaults.version)+';\nexport const catalog='+JSON.stringify(rows)+';\n');console.log('Generated 223 public catalog rows');
const cases=[...read('implementation-rules.json').cases,...read('rule-variants.json').map(r=>({...r,source_ids:r.sources,when:{service_profile:r.scope},reference_months:r.months,selected_months:r.months,reset_action:r.action==='교환'?'replace':r.action==='청소'?'clean':'inspect'}))];
fs.writeFileSync(path.join(root,'ui','research-profiles.js'),'// Generated public profile and companion data.\nexport const profiles='+JSON.stringify(cases)+';\nexport const laborBundles='+JSON.stringify(read('labor-bundles.json'))+';\nexport const sources='+JSON.stringify([...read('sources.json'),...read('preventive-sources.json'),...read('implementation-sources.json')])+';\nexport const batteryTypes='+JSON.stringify(read('batteries.json').types)+';\n');
