const {chromium}=require(process.env.VEHICLE_PLAYWRIGHT_PATH||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const reveal=require('./reveal-tool.cjs');
(async()=>{const browser=await chromium.launch();try{
 const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[],snapshots=[];
 const output=path.resolve(__dirname,'../ui/evidence/copy-031');fs.mkdirSync(output,{recursive:true});
 page.on('pageerror',e=>errors.push(e.message));await page.route('https://api.github.com/**',r=>r.fulfill({json:{tag_name:'v0.3.0'}}));
 await page.goto('http://127.0.0.1:4179');await page.locator('.nav-item').first().waitFor();
 async function capture(name){const visible=await page.locator('body').innerText();assert.ok(!/Telegram|텔레그램|시안|초기 앱|시험 알림|웹 미리보기|이 브라우저|내 기록/.test(visible),name+' has development copy');assert.equal(await page.locator('.app-header .demo-badge').count(),0);await page.screenshot({path:path.join(output,name+'.png')});snapshots.push({name,text:visible});}
 await capture('01-empty');
 await page.locator('[data-add-vehicle]').click();await capture('02-registration');await page.locator('#sheet-close').click();
 await page.evaluate(async()=>{const v={id:'copy-fixture',name:'우리집 SUV',meta:'가솔린 · 자동변속기',conditions:{fuel:'gasoline',transmission:'at',drive:'2wd',battery:'agm'},managePacks:['basic','major','long','body'],managementMode:'all',points:[['2026-08-18',49200],['2026-08-28',49700],['2026-09-07',50200]],history:[{id:'h1',visitId:'v1',date:'2026-08-18',km:49200,name:'엔진오일 교환',action:'replace',cost:80000,shop:'동네 정비소',memo:'필터 함께 교환',assetIds:['oil'],revisions:[{at:'2026-08-19',before:{date:'2026-08-18',km:49000,cost:70000},after:{date:'2026-08-18',km:49200,cost:80000}}]}],services:[{id:'oil',name:'엔진오일',icon:'oil',pack:'basic',intervalKm:10000,intervalMonths:12,lastDate:'2026-08-18',lastKm:49200},{id:'brake',name:'브레이크액',icon:'drop',pack:'basic',intervalKm:50000,intervalMonths:24,lastDate:'2024-09-28',lastKm:10000},{id:'cabin',name:'에어컨 필터',pack:'basic',intervalKm:10000,intervalMonths:12,lastDate:'2025-09-28',lastKm:41000}],yearCost:80000};await(await import('/local-store.js')).writeState({version:1,activeVehicleId:v.id,vehicles:[v],receipts:[]},[]);});await page.reload();await page.locator('.vehicle-name').waitFor();
 await capture('03-home');
 await page.locator('.bottom-nav [data-page="upcoming"]').click();await capture('04-upcoming');
 await page.locator('[data-service="brake"]').click();await capture('05-service-detail');await page.locator('#sheet-close').click();
 await page.locator('.bottom-nav [data-page="add"]').click();await capture('06-record-menu');
 await page.locator('[data-entry="photo"]').click();await capture('07-photo');await page.locator('#sheet-close').click();
 await page.locator('.bottom-nav [data-page="add"]').click();await page.locator('[data-entry="manual"]').click();await capture('08-item-picker');await page.locator('[data-pick-item="oil"]').click();await capture('09-record-form');await page.locator('#sheet-close').click();
 await page.locator('.bottom-nav [data-page="history"]').click();await capture('10-history');await page.locator('[data-history="0"]').click();await capture('11-history-detail');await page.locator('#sheet-body').getByText(/날짜·거리·비용 변경 이력/).click();assert.ok(!(await page.locator('#sheet-body').innerText()).includes('"km":'));await page.locator('#sheet-close').click();
 await page.locator('.bottom-nav [data-page="manage"]').click();await capture('12-manage');
 await reveal(page,'[data-notifications]');await capture('13-notifications');assert.equal(await page.locator('#test-notification').isVisible(),false);await page.getByText('알림이 오지 않나요?',{exact:true}).click();assert.equal(await page.locator('#test-notification').isVisible(),true);await page.locator('#sheet-close').click();
 await reveal(page,'[data-backup]');await capture('14-backup');assert.match(await page.locator('#sheet-body').innerText(),/암호화되지 않은/);await page.locator('#sheet-close').click();
 await reveal(page,'[data-app-info]');const box=await page.locator('#startup-update').boundingBox();assert.ok(box.width<=24&&box.height<=24);const fold=page.locator('#sheet-body summary');await fold.focus();await page.keyboard.press('Enter');assert.equal(await fold.evaluate(el=>el.parentElement.open),true);await page.keyboard.press('Enter');assert.equal(await fold.evaluate(el=>getComputedStyle(el).display),'list-item');await capture('15-app-info');await page.locator('#check-update').click();await page.waitForFunction(()=>!document.querySelector('#check-update').disabled);await page.locator('#startup-update').uncheck();await page.reload();await page.locator('.bottom-nav [data-page="manage"]').click();await reveal(page,'[data-app-info]');assert.equal(await page.locator('#startup-update').isChecked(),false);await page.locator('#sheet-close').click();
 await page.locator('[data-service="oil"]').click();await page.locator('[data-edit-period]').click();await capture('16-rule-editor');await page.locator('#sheet-close').click();
 const before=await page.evaluate(async()=>await(await import('/local-store.js')).readState());
 for(const width of [320,390,475,768,1280])for(const font of [100,200]){await page.setViewportSize({width,height:900});await page.evaluate(font=>document.documentElement.style.fontSize=font+'%',font);for(const id of ['home','upcoming','history','manage']){await page.locator('.bottom-nav [data-page="'+id+'"]').click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,id+' '+width+' '+font);}}
 const after=await page.evaluate(async()=>await(await import('/local-store.js')).readState());assert.deepEqual(after,before);assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(output,'screens.json'),JSON.stringify(snapshots,null,2));console.log('PASS: 16 screens/dialogs; no development copy/header badge; update controls in management; diagnostic help folded; safety warnings retained; 5 widths x 2 font sizes x 4 pages; persisted data unchanged; no browser errors.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
