import {showRecoveries} from './recovery-view.js';
import {encodeBackup,decodeBackup,restoreBackup,exportFile,MAX_BACKUP} from './backup.js';
import {readState} from './local-store.js';
import {escape as esc} from './components.js';
export function openBackup(open,setBusy=()=>{}){
 open('백업·복원',`<p>차량·정비 기록과 사진을 함께 보관합니다.</p><p class="demo-warning">개인정보가 포함된 암호화되지 않은 파일입니다. 안전한 곳에 보관하세요.</p><button class="primary-button" id="export-backup">백업 파일 저장</button><label for="import-backup">백업 파일 불러오기 (최대 50 MB)</label><input id="import-backup" type="file" accept=".json,application/json"><p id="backup-result" role="status"></p><div id="backup-preview"></div><h3>최근 저장본</h3><button class="secondary-button" id="show-recoveries">최근 저장본 확인</button><div id="recovery-list"></div>`);
 document.querySelector('#show-recoveries').onclick=()=>showRecoveries(document.querySelector('#recovery-list'),setBusy);
 const result=document.querySelector('#backup-result'),preview=document.querySelector('#backup-preview'),input=document.querySelector('#import-backup'),button=document.querySelector('#export-backup');
 button.onclick=async()=>{button.disabled=true;try{const snapshot=await readState();if(!snapshot)throw Error('먼저 주행거리나 차량 메모를 저장해 주세요.');const r=await exportFile(await encodeBackup(snapshot));result.textContent=r.cancelled?'저장을 취소했어요.':r.download?'다운로드를 요청했어요. 다운로드 폴더를 확인해 주세요.':'백업 파일을 저장했어요.';}catch(e){result.textContent='백업 실패: '+e.message;}finally{button.disabled=false;}};
 input.onchange=async()=>{preview.textContent='';input.disabled=true;try{const file=input.files[0];if(!file)return;if(file.size>MAX_BACKUP)throw Error('50 MB 이하만 지원합니다.');const snapshot=await decodeBackup(await file.text());result.textContent='백업 검사를 통과했어요.';preview.innerHTML=`<p>차량 ${snapshot.state.vehicles.length}대 · 기록 ${snapshot.state.vehicles.reduce((n,v)=>n+v.history.length,0)}건 · 사진 ${snapshot.photos.length}장</p><p>${snapshot.state.vehicles.map(v=>esc(v.name)).join(', ')}</p><p>현재 기록을 유지하고 별도 차량으로 추가합니다. 같은 파일을 다시 복원하면 중복 차량이 생깁니다.</p><button class="primary-button" id="confirm-restore">별도 차량으로 복원</button>`;document.querySelector('#confirm-restore').onclick=async()=>{document.querySelector('#confirm-restore').disabled=true;input.disabled=true;button.disabled=true;setBusy(true);try{await restoreBackup(snapshot);setBusy(false);location.reload();}catch(e){setBusy(false);result.textContent='복원 실패. 기존 기록은 유지됩니다: '+e.message;document.querySelector('#confirm-restore').disabled=false;input.disabled=false;button.disabled=false;}};}catch(e){result.textContent='불러오지 않았어요: '+e.message;}finally{input.disabled=false;}};
}
