import {createLinkEditor} from './link-editor.js';
import {catalog} from './catalog-data.js';
import {linkHistory,confirmLink,ensureCatalog} from './catalog-link.js';
import {escape as esc} from './components.js';
import {sync,periodText} from './schedule.js';
const names={present:'관리 중',unknown:'장착 확인 필요',absent:'차량 조건상 제외'};
export function createCatalogView({getVehicle,open,mutate,editRule}){
 function show(){const v=getVehicle();open('전체 관리항목 · 223개',`<p>차량 조건과 장착 여부를 구분합니다. 모르는 부품을 미장착으로 간주하지 않아요.</p><input id="catalog-search" aria-label="관리항목 검색" placeholder="부품명 또는 계통 검색"><div id="catalog-results"></div>`);const draw=()=>{const q=document.querySelector('#catalog-search').value.trim();document.querySelector('#catalog-results').innerHTML=catalog.filter(r=>(r.name+r.system).includes(q)).map(r=>{const s=v.services.find(s=>s.id===r.id);return `<button class="option" data-catalog-id="${r.id}"><span><strong>${esc(r.name)}</strong><small>${esc(r.system)} · ${names[s?.fitment||'unknown']}</small></span></button>`;}).join('');document.querySelectorAll('[data-catalog-id]').forEach(b=>b.onclick=()=>detail(b.dataset.catalogId));};document.querySelector('#catalog-search').oninput=draw;draw();}
 function detail(id){const v=getVehicle(),row=catalog.find(r=>r.id===id),s=v.services.find(s=>s.id===id);if(!row||!s)return;
 const supported=['ENG-01','ENG-02','TIM-03','TIM-06','FUE-04','AIR-01','BRK-01','AC-01','ELE-12'].includes(id);
 open(row.name,`<div class="service-form"><p>${esc(row.applicability)}</p><p>${esc(row.criteria)}</p><p class="field-help">복합 항목은 실제 교환한 하위 부품에만 적용합니다. 제어기나 본체 전체를 교환한 것으로 처리하지 않아요.</p><p>관리 방식: ${esc(row.mode)}<br>현재 설정: ${periodText(s)}</p><button id="split-component" class="secondary-button">세부 부품을 별도 항목으로 관리</button><button id="complete-rule-open" class="primary-button">주기·작업·최초/반복 기준 설정</button><label for="asset-fitment">실제 장착 여부</label><select id="asset-fitment"><option value="unknown">모름</option><option value="present">장착 확인</option><option value="absent">미장착 확인</option></select><button class="secondary-button" id="save-fitment">장착 여부 저장</button>${row.proposedKm||row.proposedMonths?`<p>조사된 선택형 예방안: ${periodText({intervalKm:row.proposedKm,intervalMonths:row.proposedMonths})}</p><p class="demo-warning">제조사 공통 주기나 보증 수명이 아닙니다. 실제 부품·회로·조건에 맞는 더 이른 기준이 있으면 우선하세요.</p>${supported?'<label class="check-option"><input id="accept-preventive" type="checkbox">장착 부품과 적용 범위를 확인했고, 이 예방안을 선택합니다.</label><button class="primary-button" id="activate-rule">예방주기 적용</button>':'<p>구조·하위 부품·제조일 또는 작업 종류에 따라 달라지는 항목입니다. 이 범용 수치는 자동 적용하지 않습니다.</p>'}`:'<p>공통 고정 교환주기 대신 상태·작업 사건 또는 정확한 부품별 기준으로 관리합니다.</p>'}<p id="catalog-error" role="alert"></p><p class="field-help">근거 식별자: ${esc((row.sources||[]).join(', '))}</p></div>`);
 document.querySelector('#split-component').onclick=()=>{open('세부 부품 추가',`<p>${esc(row.name)} 안에서 실제 관리할 부품을 구분합니다. 기존 이력과 주기는 복사하지 않습니다.</p><label>구체적인 부품 이름<input id="split-name" maxlength="100" placeholder="예: 커플링 오일필터"></label><button id="split-save" class="primary-button">별도 관리항목 만들기</button><p id="split-error"></p>`);document.querySelector('#split-save').onclick=()=>{const name=document.querySelector('#split-name').value.trim();if(!name){document.querySelector('#split-error').textContent='구체적인 부품 이름이 필요합니다.';return;}const child=sync({id:'part-'+crypto.randomUUID(),catalogComponentId:id,name,pack:s.pack,fitment:'present',fitmentConfirmedByUser:true,lastDate:null,lastKm:null,intervalKm:null,intervalMonths:null,basis:'사용자가 분리한 세부 부품'});mutate(()=>v.services.push(child),'세부 부품을 추가했어요');editRule(child);};};document.querySelector('#complete-rule-open').onclick=()=>editRule(s);document.querySelector('#asset-fitment').value=s.fitment;document.querySelector('#save-fitment').onclick=()=>{const value=document.querySelector('#asset-fitment').value;mutate(()=>{s.fitment=value;s.fitmentConfirmedByUser=true;},'장착 여부를 저장했어요');detail(id);};const button=document.querySelector('#activate-rule');if(button)button.onclick=()=>{if(s.fitment!=='present'||!document.querySelector('#accept-preventive').checked){document.querySelector('#catalog-error').textContent='장착 확인과 예방안 선택 동의가 필요합니다.';return;}mutate(()=>{s.intervalKm=row.proposedKm;s.intervalMonths=row.proposedMonths;s.userPeriodChanged=true;s.basis='사용자가 선택한 예방안 · 제조사 공통 기준 아님';sync(s);},'예방주기를 적용했어요');detail(id);};
 }
 function connect(){mutate(()=>linkHistory(getVehicle()),'과거 기록과 관리항목을 연결했어요');review();}
 function review(){const v=getVehicle(),links=v.maintenanceLinks||[],unknown=links.filter(l=>!l.confirmed);open('과거 기록 연결',`<p>연결 ${links.length}건 · 교환/작업 확인 필요 ${unknown.length}건</p><p>원문 방문 기록과 비용은 그대로 보존합니다. 연결 기록은 비용을 추가 합산하지 않습니다. 날짜 없는 원문은 자동 주기 계산에 넣지 않습니다.</p>${unknown.map((l,i)=>`<section class="record-note service-form"><strong>${esc(l.date)} · ${l.km.toLocaleString()} km</strong><p>${esc(v.services.find(s=>s.id===l.componentId)?.name||l.componentId)}<br>${esc(l.text)}</p><select id="link-action-${i}" aria-label="작업 종류"><option value="">실제 작업 선택</option><option value="replace">교환 완료</option><option value="inspect">점검</option><option value="clean">청소</option><option value="refill">보충</option><option value="other">기타 수리</option></select><button class="secondary-button" data-confirm-link="${i}">확인 기록</button></section>`).join('')||'<p>확인이 필요한 연결 기록이 없습니다.</p>'}<details><summary>확인된 연결 보기</summary>${links.filter(l=>l.confirmed).map(l=>`<p>${esc(l.date)} · ${esc(v.services.find(s=>s.id===l.componentId)?.name||l.componentId)} · ${esc({replace:'교환',inspect:'점검',clean:'청소',refill:'보충',adjust:'조정·위치교환',other:'수리·기타'}[l.action]||'확인 필요')}<br>${esc(l.text)}</p>`).join('')}</details>`);document.querySelectorAll('[data-confirm-link]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.confirmLink),action=document.querySelector('#link-action-'+i).value;if(!action)return;mutate(()=>confirmLink(v,unknown[i].key,action),'작업 종류를 확인했어요');review();});}
 return {show,connect,review:createLinkEditor({getVehicle,open,mutate})};
}
