import {escape as esc,fmt,icon} from './components.js';
import {receiptHTML} from './receipts.js';
import {APP_MODE} from './runtime.js';
import {actions} from './ledger.js';
export const recordDate=h=>h.date||'2026-'+String(parseInt(h.month)).padStart(2,'0')+'-'+String(h.day).padStart(2,'0');
export const recordAction=h=>h.action||(/교환$/.test(h.name)?'replace':/점검$/.test(h.name)?'inspect':'other');
export function visits(history){const map=new Map();history.forEach((h,i)=>{if(h.deletedAt)return;const key=h.visitId?'visit:'+h.visitId:'record:'+i;if(!map.has(key))map.set(key,{index:i,date:recordDate(h),items:[]});map.get(key).items.push(h);});return [...map.values()].sort((a,b)=>b.date.localeCompare(a.date));}
export function filterVisits(history,q='',filter='all'){const needle=q.trim().toLowerCase();return visits(history).filter(g=>g.items.some(h=>(!needle||[h.name,h.shop,h.memo,h.note].filter(Boolean).join(' ').toLowerCase().includes(needle))&&(filter==='all'||(filter==='other'?!['replace','inspect'].includes(recordAction(h)):recordAction(h)===filter||h._actions?.includes(filter)))));}
const total=g=>g.items.some(h=>h.cost!==null&&h.cost!==undefined)?g.items.reduce((n,h)=>n+(h.cost??0),0):null;
export function createHistory({getVehicle,open,mutate}){
 let query='',filter='all',vehicleId=null;
 function reset(){query='';filter='all';vehicleId=getVehicle().id;}
 function results(){const v=getVehicle(),groups=filterVisits(v.history.map(h=>({...h,_actions:(v.maintenanceLinks||[]).filter(l=>l.visitId===h.visitId&&!l.deletedAt).map(l=>l.action)})),query,filter);return `<p class="history-result-count" role="status">${groups.length}건의 방문 기록 · 검색 결과는 방문 전체를 보여줘요</p>${groups.length?groups.map(g=>`<button class="history-row visit-card" data-history="${g.index}"><span class="visit-top"><strong>${esc(g.date.replaceAll('-','. '))}</strong><span>${total(g)===null?'비용 미입력':fmt(total(g))+'원'}</span></span><span class="visit-title">${esc(g.items[0].name)}${g.items.length>1?' 외 '+(g.items.length-1)+'건':''}</span><span class="visit-meta">${fmt(g.items[0].km)} km${g.items[0].shop?' · '+esc(g.items[0].shop):''}${g.items.some(h=>h.receiptId)?' · 사진 첨부':''}</span></button>`).join(''):`<div class="empty">${icon('history')}<h3>${v.history.length?'찾는 기록이 없어요':'아직 정비 기록이 없어요'}</h3><p>${v.history.length?'검색어나 작업 종류를 바꿔보세요.':'첫 정비 기록부터 남겨보세요.'}</p>${v.history.length?'<button class="secondary-button" id="history-reset">검색 초기화</button>':'<button class="secondary-button" data-page="add">기록 추가</button>'}</div>`}`;}
 function page(){if(vehicleId!==getVehicle().id)reset();return `<h1 class="page-heading">정비 이력</h1><p class="muted-note">차곡차곡 남긴 내 차의 기록</p><label class="history-search-label" for="history-search">기록 검색</label><input id="history-search" type="search" maxlength="100" placeholder="부품명 · 정비소 · 메모" value="${esc(query)}"><div class="history-filters" aria-label="작업 종류">${[['all','전체'],['replace','교환'],['inspect','점검'],['other','기타']].map(([id,name])=>`<button data-history-filter="${id}" aria-pressed="${id===filter}">${name}</button>`).join('')}</div><div id="history-results">${results()}</div>`;}
 function bind(){const input=document.querySelector('#history-search');if(!input)return;const refresh=()=>{document.querySelector('#history-results').innerHTML=results();const resetButton=document.querySelector('#history-reset');if(resetButton)resetButton.onclick=()=>{reset();input.value='';paint();refresh();input.focus();};};
  const paint=()=>document.querySelectorAll('[data-history-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.historyFilter===filter)));
  input.oninput=()=>{query=input.value;refresh();};document.querySelectorAll('[data-history-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.historyFilter;paint();refresh();});refresh();
 }
 function detail(index){const v=getVehicle(),h=v.history[index];if(!h)return;const group=h.visitId?v.history.filter(x=>x.visitId===h.visitId&&!x.deletedAt):[h];const receiptIds=[...new Set(group.map(x=>x.receiptId).filter(Boolean))];
  open(group.length>1?'한 번에 남긴 정비 기록':h.name,`<p class="detail-vehicle">${esc(v.name)}</p><dl class="detail-list"><div><dt>날짜</dt><dd>${esc(recordDate(h))}</dd></div><div><dt>주행거리</dt><dd>${fmt(h.km)} km</dd></div><div><dt>방문 총비용</dt><dd>${total({items:group})===null?'비용 미입력':fmt(total({items:group}))+'원'}</dd></div></dl>${group.length>1?'<p class="field-help">총비용은 방문 기준입니다. 개별 부품별 비용을 뜻하지 않아요.</p>':''}${group.map(item=>`<section class="history-detail-item"><h3>${esc(item.name)}</h3><p class="record-note">${esc(item.note||'')}</p><p class="record-note">정비소: ${esc(item.shop||'미입력')}</p><p class="record-note">${esc(item.memo||'메모 없음')}</p><button class="secondary-button" data-history-edit="${v.history.indexOf(item)}">정비소·메모 수정</button><details><summary>수정 이력 ${(item.edits||[]).length}건</summary>${(item.edits||[]).map(e=>`<p class="record-note">${esc(new Date(e.at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}))}<br>정비소: ${esc(e.before.shop||'미입력')} → ${esc(e.after.shop||'미입력')}<br>메모: ${esc(e.before.memo||'없음')} → ${esc(e.after.memo||'없음')}</p>`).join('')||'<p class="muted-note">수정한 기록이 없어요.</p>'}</details></section>`).join('')}${APP_MODE?`${group.map(item=>`<details><summary>날짜·거리·비용 변경 이력 ${(item.revisions||[]).length}건</summary>${(item.revisions||[]).map(r=>`<p>${esc(r.at)}<br>${esc(JSON.stringify(r.before))}<br>→ ${esc(JSON.stringify(r.after))}</p>`).join('')}</details>`).join('')}<h3>부품별 작업</h3>${(v.maintenanceLinks||[]).filter(l=>l.visitId===h.visitId&&!l.deletedAt).map(l=>`<p>${esc(v.services.find(s=>s.id===l.componentId)?.name||l.componentId)} · ${esc(actions[l.action]||'확인 필요')}<br>${esc(l.text)}</p>`).join('')}<button class="secondary-button" data-review-links>부품 연결 수정·추가</button>${group.map(item=>`<button class="secondary-button" data-full-edit="${v.history.indexOf(item)}">날짜·거리·비용·작업 수정</button><button class="secondary-button" data-remove-record="${v.history.indexOf(item)}">이 기록 삭제</button>`).join('')}`:''}${receiptIds.map(id=>receiptHTML(id)).join('')}`);
  document.querySelectorAll('[data-history-edit]').forEach(b=>b.onclick=()=>edit(Number(b.dataset.historyEdit)));
 }
 function edit(index){const v=getVehicle(),h=v.history[index];open('정비소·메모 수정',`<p class="detail-vehicle">${esc(v.name)} · ${esc(h.name)}</p><form class="service-form" id="history-edit-form"><label for="history-shop">정비소</label><input id="history-shop" maxlength="120" value="${esc(h.shop||'')}"><label for="history-memo">메모</label><textarea id="history-memo" maxlength="1000" rows="4">${esc(h.memo||'')}</textarea><p class="demo-warning">이 항목의 메모만 바꿔요. 날짜·거리·비용·교환주기는 변경하지 않습니다. 새로고침하면 초기화됩니다.</p><button type="submit" class="primary-button">수정 저장</button><button type="button" id="history-edit-cancel" class="secondary-button">취소</button></form>`);
  document.querySelector('#history-edit-cancel').onclick=()=>detail(index);document.querySelector('#history-edit-form').onsubmit=e=>{e.preventDefault();if(v.id!==getVehicle().id)return;const before={shop:h.shop||'',memo:h.memo||''},after={shop:document.querySelector('#history-shop').value.trim(),memo:document.querySelector('#history-memo').value.trim()};if(before.shop!==after.shop||before.memo!==after.memo)mutate(()=>{h.edits=[...(h.edits||[]),{at:new Date().toISOString(),before,after}];Object.assign(h,after);},'정비소·메모를 수정했어요');detail(index);};
 }
 return {page,bind,detail,reset};
}
