import {sync,validDate} from './schedule.js';
import {TODAY} from './runtime.js';
export const actions={replace:'교환',inspect:'점검',clean:'청소',refill:'보충',adjust:'조정·위치교환',lubricate:'윤활',other:'수리·기타'};
export const activeRecords=v=>v.history.filter(h=>!h.deletedAt);
export function migrateLedger(v){
 for(const h of v.history)h.id??=crypto.randomUUID();
 v.odometerEntries??=v.points.filter(p=>!v.history.some(h=>h.date===p[0]&&h.km===p[1])).map(p=>({id:crypto.randomUUID(),date:p[0],km:p[1]}));
 for(const s of [...v.services,...(v.planned||[])])if(!s.ledgerBase){const represented=v.history.some(h=>h.assetIds?.includes(s.id)&&h.date===s.lastDate)||(v.maintenanceLinks||[]).some(l=>l.componentId===s.id&&l.date===s.lastDate);s.ledgerBase=represented?{lastDate:null,lastKm:null,manufactureDate:s.manufactureDate??null}:{manufactureDate:s.manufactureDate??null,lastDate:s.lastDate??null,lastKm:s.lastKm??null,basisKm:s.basisKm??null};}
}
export function observations(v,excludeId){return [...(v.odometerEntries||[]).filter(x=>!x.deletedAt&&x.id!==excludeId),...activeRecords(v).filter(h=>h.id!==excludeId)].filter(h=>validDate(h.date)&&Number.isFinite(h.km));}
export function checkObservation(v,date,km,excludeId){if(!validDate(date)||date>TODAY())throw Error('오늘까지의 올바른 날짜를 입력해 주세요.');if(!Number.isSafeInteger(km)||km<0||km>999999)throw Error('주행거리는 0~999,999 km 정수로 입력해 주세요.');for(const p of observations(v,excludeId)){if(p.date===date&&p.km!==km)throw Error('같은 날짜의 다른 기록과 주행거리가 다릅니다.');if(p.date<date&&p.km>km||p.date>date&&p.km<km)throw Error('다른 날짜의 실측 주행거리와 순서가 맞지 않습니다.');}}
export function recalculate(v){migrateLedger(v);const records=activeRecords(v),links=(v.maintenanceLinks||[]).filter(l=>!l.deletedAt&&records.some(h=>h.visitId===l.visitId));
 for(const s of [...v.services,...(v.planned||[])]){const events=[...records.filter(h=>h.assetIds?.includes(s.id)).map(h=>({date:h.date,km:h.km,action:h.action,confirmed:true,basisKm:h.alignedKm,manufactureDate:h.manufactureDate})),...links.filter(l=>l.componentId===s.id)];for(const event of events)if(event.confirmed)s.fitment=s.fitment==='absent'?s.fitment:'present';const replacements=events.filter(l=>l.confirmed&&l.action==='replace').sort((a,b)=>b.date.localeCompare(a.date));const base=s.ledgerBase||{},last=replacements[0];const chosen=last&&(!base.lastDate||last.date>=base.lastDate)?last:{date:base.lastDate,km:base.lastKm,basisKm:base.basisKm};s.lastDate=chosen.date??null;s.lastKm=chosen.km??null;s.basisKm=chosen.basisKm??s.lastKm;if(s.clockOrigin==='manufactured')s.manufactureDate=chosen.date&&s.manufactureOverride?.forDate===chosen.date?s.manufactureOverride.date:(chosen.manufactureDate??s.manufactureBaseline??base.manufactureDate??null);
 const service=events.filter(e=>e.confirmed&&e.action===(s.scheduleAction||'replace')).sort((a,b)=>b.date.localeCompare(a.date))[0];s.lastServiceDate=service?.date??null;s.lastServiceKm=service?.km??null;
 const newest=events.sort((a,b)=>b.date.localeCompare(a.date))[0];s.historyNeedsReview=!!(newest&&!newest.confirmed&&(!s.lastDate||newest.date>=s.lastDate));sync(s);}
 const points=observations(v).sort((a,b)=>a.date.localeCompare(b.date)),map=new Map();v.odometerConflict=false;let last;for(const p of points){if(last&&(last.date===p.date&&last.km!==p.km||last.km>p.km))v.odometerConflict=true;map.set(p.date,p.km);last=p;}v.points=[...map];const paid=records.filter(h=>h.date?.startsWith(TODAY().slice(0,4))&&h.cost!=null);v.yearCost=paid.length?paid.reduce((n,h)=>n+h.cost,0):null;
}
export function reviseRecord(v,id,patch){migrateLedger(v);const h=v.history.find(h=>h.id===id);if(!h||h.deletedAt)throw Error('기록을 찾지 못했습니다.');const group=h.visitId?v.history.filter(r=>r.visitId===h.visitId):[h];const validation=structuredClone(v);validation.history=validation.history.filter(r=>!group.some(g=>g.id===r.id));checkObservation(validation,patch.date,patch.km,id);if(!patch.name?.trim()||!Object.hasOwn(actions,patch.action)||patch.cost!==null&&(!Number.isSafeInteger(patch.cost)||patch.cost<0||patch.cost>999999999))throw Error('이름·작업·비용을 확인해 주세요.');
 const fields=['date','km','cost','name','action','shop','memo','assetIds','alignedKm'];const before=Object.fromEntries(fields.map(k=>[k,h[k]??null]));for(const other of group.filter(r=>r!==h)){other.revisions=[...(other.revisions||[]),{at:new Date().toISOString(),before:{date:other.date,km:other.km},after:{date:patch.date,km:patch.km}}];Object.assign(other,{date:patch.date,km:patch.km,alignedKm:null,month:Number(patch.date.slice(5,7))+'월',day:String(Number(patch.date.slice(8)))});}Object.assign(h,patch,{month:Number(patch.date.slice(5,7))+'월',day:String(Number(patch.date.slice(8)))});h.revisions=[...(h.revisions||[]),{at:new Date().toISOString(),before,after:patch}];for(const l of v.maintenanceLinks||[])if(h.visitId&&l.visitId===h.visitId){l.date=h.date;l.km=h.km;/* Mixed imported actions retain their individually confirmed values. */}recalculate(v);
}
export function deleteRecord(v,id){migrateLedger(v);const h=v.history.find(h=>h.id===id);if(!h)throw Error('기록 없음');h.deletedAt=new Date().toISOString();recalculate(v);}
export function restoreRecord(v,id){const h=v.history.find(h=>h.id===id);if(!h)throw Error('기록 없음');checkObservation(v,h.date,h.km,id);delete h.deletedAt;recalculate(v);}
export function saveOdometer(v,entry){migrateLedger(v);checkObservation(v,entry.date,entry.km,entry.id);const old=v.odometerEntries.find(p=>p.id===entry.id);if(old){old.revisions=[...(old.revisions||[]),{date:old.date,km:old.km,at:new Date().toISOString()}];Object.assign(old,{date:entry.date,km:entry.km});}else v.odometerEntries.push({id:crypto.randomUUID(),date:entry.date,km:entry.km});recalculate(v);}
