import {escape as esc} from './components.js';
import {actions,checkObservation,recalculate} from './ledger.js';
import {linkHistory} from './catalog-link.js';
import {TODAY} from './runtime.js';
export function createLinkEditor({getVehicle,open,mutate}){return function review(){const v=getVehicle(),records=v.history.filter(h=>!h.deletedAt),links=(v.maintenanceLinks||[]).filter(l=>records.some(h=>h.visitId===l.visitId));
open('과거 기록 연결',`<p>부품별 작업을 수정해도 방문 비용과 원문은 유지합니다. 교환으로 확인한 부품만 교환 시점을 갱신합니다.</p><label>방문 선택<select id="link-visit">${records.map(h=>`<option value="${h.id}">${esc(h.date)} · ${esc(h.name)}</option>`).join('')}</select></label><label>부품<select id="link-part">${v.services.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></label><label>작업<select id="link-new-action">${Object.entries(actions).map(([k,t])=>`<option value="${k}">${t}</option>`).join('')}</select></label><button class="primary-button" id="add-link">선택한 방문에 부품 연결</button><p id="links-error" role="alert"></p><h3>연결된 작업 ${links.filter(l=>!l.deletedAt).length}건</h3>${links.map((l,i)=>`<section class="record-note"><strong>${esc(l.date)} · ${esc(v.services.find(s=>s.id===l.componentId)?.name||l.componentId)}</strong><p>${esc(l.text||'직접 연결')}</p><select id="existing-link-${i}"><option value="unknown">확인 필요</option>${Object.entries(actions).map(([k,t])=>`<option value="${k}" ${l.action===k?'selected':''}>${t}</option>`).join('')}</select><button class="secondary-button" data-link-save="${i}" ${l.deletedAt?'disabled':''}>작업 수정·확인</button><button class="secondary-button" data-link-toggle="${i}">${l.deletedAt?'연결 복구':'연결 해제'}</button></section>`).join('')}<h3>날짜 확인이 필요한 원문</h3>${(v.pendingRecords||[]).filter(p=>!p.resolvedRecordId).map((p,i)=>`<section><pre class="source-log">${esc(p.memo)}</pre><label>실제 정비 날짜<input type="date" max="${TODAY()}" id="pending-date-${i}"></label><label>실제 km<input inputmode="numeric" id="pending-km-${i}" value="${p.km??''}"></label><button class="secondary-button" data-resolve-pending="${i}">날짜를 확인하고 이력에 추가</button></section>`).join('')||'<p>날짜 미확인 기록이 없습니다.</p>'}`);
const change=(fn)=>{try{mutate(()=>{fn();recalculate(v);},'연결 내용을 저장했어요');review();}catch(e){document.querySelector('#links-error').textContent=e.message;}};
document.querySelector('#add-link').onclick=()=>change(()=>{const h=records.find(h=>h.id===document.querySelector('#link-visit').value),componentId=document.querySelector('#link-part').value,action=document.querySelector('#link-new-action').value;if(!h)throw Error('먼저 정비 방문을 등록하세요.');h.visitId??=h.id;if((v.maintenanceLinks||[]).some(l=>!l.deletedAt&&l.visitId===h.visitId&&l.componentId===componentId)||h.assetIds?.includes(componentId))throw Error('이미 연결된 부품입니다. 아래에서 작업을 수정하세요.');v.maintenanceLinks??=[];v.maintenanceLinks.push({key:crypto.randomUUID(),visitId:h.visitId,componentId,action,date:h.date,km:h.km,confirmed:true,confirmation:'사용자 직접 연결',text:h.memo||h.name});v.services.find(s=>s.id===componentId).fitment='present';});
document.querySelectorAll('[data-link-save]').forEach(b=>b.onclick=()=>change(()=>{const l=links[+b.dataset.linkSave],action=document.getElementById('existing-link-'+b.dataset.linkSave).value;l.revisions=[...(l.revisions||[]),{at:new Date().toISOString(),action:l.action,confirmed:l.confirmed}];Object.assign(l,{action,confirmed:action!=='unknown',confirmation:'사용자 수정'});}));
document.querySelectorAll('[data-link-toggle]').forEach(b=>b.onclick=()=>change(()=>{const l=links[+b.dataset.linkToggle];if(l.deletedAt)delete l.deletedAt;else l.deletedAt=new Date().toISOString();}));
document.querySelectorAll('[data-resolve-pending]').forEach(b=>b.onclick=()=>change(()=>{const i=+b.dataset.resolvePending,p=v.pendingRecords.filter(p=>!p.resolvedRecordId)[i],date=document.getElementById('pending-date-'+i).value,raw=document.getElementById('pending-km-'+i).value.trim(),km=raw===''?NaN:Number(raw);checkObservation(v,date,km);const id=crypto.randomUUID();v.history.push({id,visitId:id,date,km,name:'원문 날짜 확인 기록',memo:p.memo,cost:null,action:'other',sourceHash:v.sourceHash,month:Number(date.slice(5,7))+'월',day:String(Number(date.slice(8)))});p.resolvedRecordId=id;p.resolvedAt=new Date().toISOString();linkHistory(v);}));
};}
