// Native: SQLite state + private receipt files. Browser test mode: IndexedDB transaction.
const DB_NAME='vehicle-note-real-v1';
let database;
const native=()=>!!globalThis.Capacitor?.isNativePlatform?.();
async function bridge(){const {registerPlugin}=await import('/vendor/capacitor.js');return {store:registerPlugin('VehicleStore')};}
function db(){return database??=new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>req.result.createObjectStore('data');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);req.onblocked=()=>reject(Error('다른 창을 닫고 다시 열어 주세요.'));});}
export function validateState(state){if(!state||state.version!==1||!Array.isArray(state.vehicles)||!Array.isArray(state.receipts))throw Error('지원하지 않거나 손상된 저장 데이터입니다. 자동 초기화하지 않습니다.');const ids=new Set();for(const v of state.vehicles){if(typeof v.id!=='string'||ids.has(v.id)||!Array.isArray(v.history)||!Array.isArray(v.services)||!Array.isArray(v.points)||typeof v.name!=='string')throw Error('차량 데이터 형식이 올바르지 않습니다.');ids.add(v.id);}return state;}
export async function readState(){if(native()){const {store}=await bridge(),r=await store.read();if(!r.state)return null;const state=validateState(JSON.parse(r.state));const photos=await Promise.all(state.receipts.map(async p=>({...p,base64:(await store.readPhoto({id:p.id})).base64})));return {state,photos};}
 const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('data'),req=tx.objectStore('data').get('snapshot');req.onsuccess=()=>{try{if(req.result)validateState(req.result.state);resolve(req.result||null);}catch(e){reject(e);}};req.onerror=()=>reject(req.error);});}
export async function writeState(state,photos){validateState(state);if(native()){await(await bridge()).store.write({state:JSON.stringify(state),photos});return;}
 const d=await db();await new Promise((resolve,reject)=>{const tx=d.transaction('data','readwrite'),store=tx.objectStore('data'),old=store.get('snapshot');old.onsuccess=()=>{try{if(old.result&&JSON.stringify(old.result.state.vehicles)!==JSON.stringify(state.vehicles)){const previous=store.get('recovery');previous.onsuccess=()=>{try{store.put([{...old.result,savedAt:new Date().toISOString()},...(previous.result||[])].slice(0,3),'recovery');}catch(e){tx.abort();}};}store.put({state,photos},'snapshot');}catch(e){tx.abort();}};tx.oncomplete=resolve;tx.onabort=tx.onerror=()=>reject(tx.error||Error('저장 실패'));});}
export async function readRecoveries(){if(native()){const {store}=await bridge(),result=await store.readRecovery();const settled=await Promise.allSettled(result.states.map(async r=>{const state=validateState(JSON.parse(r.state));return {state,savedAt:r.savedAt,photos:await Promise.all(state.receipts.map(async p=>({...p,base64:(await store.readPhoto({id:p.id})).base64})))};}));return settled.filter(r=>r.status==='fulfilled').map(r=>r.value);}const d=await db();return new Promise((resolve,reject)=>{const request=d.transaction('data').objectStore('data').get('recovery');request.onsuccess=()=>resolve((request.result||[]).filter(r=>{try{validateState(r.state);return true;}catch{return false;}}));request.onerror=()=>reject(request.error);});}
