import {escape as esc,icon} from './components.js';
import {allServices,periodText} from './schedule.js';
export const packs=[{id:'basic',name:'기본 소모품·안전',description:'오일·필터와 제동 관련 기본 관리',ids:['oil','brake','cabin']},{id:'major',name:'주요 부품·예방정비',description:'변속기·냉각계 등 주요 부품 관리',ids:['transmission','pump']},{id:'long',name:'장기·정밀관리',description:'장기 운행에 따른 정밀관리 항목',ids:[]},{id:'body',name:'차체·편의관리',description:'차체·실내·편의장치 관리',ids:[]}];
export const inPack=(s,p)=>s.pack?s.pack===p.id:p.ids.includes(s.id);
export const selectedPacks=v=>v.managePacks||packs.map(p=>p.id);
export function createManage({getVehicle,open,close,mutate}){
 function page(){const v=getVehicle(),services=allServices(v),selected=selectedPacks(v);return `<h1 class="page-heading">내 차 관리</h1><p class="muted-note">내가 챙길 만큼, 편하게 골라보세요.</p><button class="manage-info" data-manage-info>${icon('car')}<span><strong>${esc(v.name)}</strong><small>차량 정보 · 번호판 · 규격 · 메모</small></span>${icon('right')}</button><h2 class="manage-heading">관리묶음</h2><p class="field-help">이 화면의 표시 범위만 바꿔요. 기록과 정비 예정은 유지됩니다.</p><div class="manage-packs">${packs.map(p=>`<button data-pack="${p.id}" class="manage-pack"><span class="manage-pack-top"><strong>${p.name}</strong><span>${selected.includes(p.id)?'표시 중':'숨김'}</span></span><small>${p.description}</small><span class="manage-pack-count">현재 등록 ${services.filter(s=>inPack(s,p)).length}개 · 내용 보기</span></button>`).join('')}</div><h2 class="manage-heading">항목별 관리 기준</h2>${packs.filter(p=>selected.includes(p.id)).map(p=>`<details class="manage-group"><summary>${p.name} · ${services.filter(s=>inPack(s,p)).length}개</summary>${rows(services.filter(s=>inPack(s,p)))}</details>`).join('')}${services.some(s=>!packs.some(p=>inPack(s,p)))?`<details class="manage-group"><summary>직접 추가 · 미분류 항목</summary>${rows(services.filter(s=>!packs.some(p=>inPack(s,p))))}</details>`:''}<p class="field-help">${v.catalogVersion?'전체 목록 223개 중 장착이 확인된 항목을 표시합니다. 모르는 항목은 전체 목록에서 확인하세요.':'전체 관리항목 연결 버튼으로 조사된 목록과 과거 기록을 연결할 수 있어요.'}</p><button class="secondary-button" data-manage-alert>알림 기준 확인</button>`;}
 function rows(items){return items.length?items.map(s=>`<div class="manage-rule"><strong>${esc(s.name)}</strong><span>${periodText(s)}</span><button class="secondary-button" data-edit-period="${s.id}">주기 변경</button></div>`).join(''):'<p class="muted-note">현재 등록된 항목이 없어요. 묶음 선택만으로 부품이나 주기를 자동 추가하지 않습니다.</p>';}
 function pack(id){const v=getVehicle(),p=packs.find(p=>p.id===id);if(!p)return;const items=allServices(v).filter(s=>inPack(s,p)),selected=selectedPacks(v);open(p.name,`<p class="detail-vehicle">${esc(v.name)} · 현재 등록 ${items.length}개</p><p>${p.description}</p>${rows(items)}<p class="demo-warning">표시를 꺼도 기록·교환주기·정비 예정은 삭제되지 않아요.</p><button class="primary-button" id="apply-pack">${selected.includes(id)?'이 관리묶음 숨기기':'이 관리묶음 표시하기'}</button>`);document.querySelector('#apply-pack').onclick=()=>{mutate(()=>{v.managePacks=selected.includes(id)?selected.filter(x=>x!==id):[...selected,id];},'관리 화면 표시 범위를 변경했어요');close();};}
 function info(){const v=getVehicle(),d=v.details||{};open('차량 정보',`<p class="detail-vehicle">${esc(v.name)} · ${esc(v.meta)}</p><form id="vehicle-details" class="service-form">${[['plate','번호판',20],['vin','차대번호',17],['spec','규격·장착 부품 정보',500],['note','원문 메모',5000]].map(([key,label,max])=>`<label for="vehicle-${key}">${label} (선택)</label>${key==='spec'||key==='note'?`<textarea id="vehicle-${key}" rows="3" maxlength="${max}">${esc(d[key]||'')}</textarea>`:`<input id="vehicle-${key}" maxlength="${max}" value="${esc(d[key]||'')}">`}`).join('')}<p class="field-help">번호판·차대번호는 홈에 표시하지 않습니다.</p><button class="primary-button" type="submit">차량 정보 저장</button></form>`);document.querySelector('#vehicle-details').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(['plate','vin','spec','note'].map(key=>[key,document.querySelector('#vehicle-'+key).value.trim()]));mutate(()=>{v.details=data;},'예시 차량 정보를 저장했어요');close();};}
 function alerts(){open('알림 기준',`<dl class="detail-list"><div><dt>거리</dt><dd>1,000 km 이내</dd></div><div><dt>기간</dt><dd>30일 이내</dd></div><div><dt>확인 시간</dt><dd>한국시간 오전 9시대</dd></div></dl><p>거리 또는 기간 중 하나라도 해당하면 안내하는 기획입니다.</p><p class="demo-warning">이 웹 시안은 알림을 발송하지 않습니다. 기존 텔레그램 봇의 설정도 변경하지 않아요. 실제 알림 연결 전까지 기준 확인만 제공합니다.</p>`);}
 return {page,pack,info,alerts};
}
