import {allServices,timeline} from './schedule.js';
import {TODAY} from './runtime.js';
import {escape as esc} from './components.js';
export function notificationPlan(vehicles,start=TODAY(),days=366){const entries=[];for(const v of vehicles.filter(v=>!v.deletedAt&&v.notificationEnabled))for(const s of allServices(v).filter(s=>s.enabled!==false)){let previous=null;for(let i=0;i<days;i++){const date=new Date(Date.parse(start)+i*86400000).toISOString().slice(0,10),t=timeline(v,s,date);const stage=['soon','overdue'].includes(t.status)?t.status:null;if(stage&&stage!==previous){entries.push({key:[v.id,s.id,s.scheduleAction||'replace',s.clockDate||s.lastDate||'',s.clockKm??s.lastKm??'',stage].join('|'),start:date,end:date,stage});}else if(stage&&entries.length)entries.at(-1).end=date;previous=stage;}}return {enabled:vehicles.some(v=>!v.deletedAt&&v.notificationEnabled),entries,generatedAt:start,expiresAt:new Date(Date.parse(start)+(days-1)*86400000).toISOString().slice(0,10)};}
async function bridge(){const {registerPlugin}=await import('/vendor/capacitor.js');return {plugin:registerPlugin('VehicleNotifications')};}
export async function syncNotifications(vehicles){if(!globalThis.Capacitor?.isNativePlatform?.())return;await(await bridge()).plugin.configure({plan:JSON.stringify(notificationPlan(vehicles))});}
export function openNotificationSettings({getVehicle,getVehicles,open,mutate}){const v=getVehicle();open('앱 알림 설정',`<p class="detail-vehicle">${esc(v.name)}</p><p>정비까지 1,000 km 또는 30일 남으면 오전 9시대에 알려드려요.</p><label class="check-option notification-check"><input id="notifications-enabled" type="checkbox" ${v.notificationEnabled?'checked':''}>이 차량 정비 알림 사용</label><button id="save-notifications" class="primary-button">알림 설정 저장</button><details class="detail-fold"><summary>알림이 오지 않나요?</summary><button id="test-notification" class="secondary-button">알림 수신 확인</button><p>알림 권한과 배터리 절전 설정을 확인하세요. 앱을 강제 중지했다면 다시 열어 주세요.</p></details><p id="notification-status" role="status"></p><details class="detail-fold"><summary>알림 기준 자세히</summary><p>한국시간 오전 9시대 기준이며 절전 상태에 따라 늦어질 수 있습니다. 같은 정비 회차·단계는 한 번 알리고, 기한이 지나면 다시 안내합니다.</p><p>주행거리를 90일 넘게 갱신하지 않으면 거리 추정 알림은 중단합니다. 날짜 기준 알림은 유지합니다. 앱을 열거나 기록을 저장하면 향후 1년의 알림 계획을 갱신합니다.</p></details>`);
 document.querySelector('#save-notifications').onclick=async()=>{const status=document.querySelector('#notification-status');try{const enabled=document.querySelector('#notifications-enabled').checked;if(enabled&&globalThis.Capacitor?.isNativePlatform?.()){const result=await(await bridge()).plugin.enable();if(!result.granted){status.textContent='알림 권한이 꺼져 있습니다. 시스템 설정에서 허용해 주세요.';return;}}mutate(()=>{v.notificationEnabled=enabled;},'알림 설정을 저장했어요');status.textContent=enabled?'알림 사용으로 설정했습니다.':'이 차량 알림을 껐습니다.';}catch(e){status.textContent='설정 실패: '+e.message;}};
 document.querySelector('#test-notification').onclick=async()=>{const status=document.querySelector('#notification-status');try{if(!globalThis.Capacitor?.isNativePlatform?.()){status.textContent='알림 수신 확인은 Android 앱에서 사용할 수 있어요.';return;}await(await bridge()).plugin.test();status.textContent='확인 알림을 보냈어요. 휴대폰 알림창을 확인해 주세요.';}catch(e){status.textContent='권한과 시스템 알림 설정을 확인해 주세요.';}};
}
