import {allServices,timeline} from './schedule.js';
import {TODAY} from './runtime.js';
import {escape as esc} from './components.js';
export function notificationPlan(vehicles,start=TODAY(),days=366){const entries=[];for(const v of vehicles.filter(v=>!v.deletedAt&&v.notificationEnabled))for(const s of allServices(v).filter(s=>s.enabled!==false)){let previous=null;for(let i=0;i<days;i++){const date=new Date(Date.parse(start)+i*86400000).toISOString().slice(0,10),t=timeline(v,s,date);const stage=['soon','overdue'].includes(t.status)?t.status:null;if(stage&&stage!==previous){entries.push({key:[v.id,s.id,s.scheduleAction||'replace',s.clockDate||s.lastDate||'',s.clockKm??s.lastKm??'',stage].join('|'),start:date,end:date,stage});}else if(stage&&entries.length)entries.at(-1).end=date;previous=stage;}}return {enabled:vehicles.some(v=>!v.deletedAt&&v.notificationEnabled),entries,generatedAt:start,expiresAt:new Date(Date.parse(start)+(days-1)*86400000).toISOString().slice(0,10)};}
async function bridge(){const {registerPlugin}=await import('/vendor/capacitor.js');return {plugin:registerPlugin('VehicleNotifications')};}
export async function syncNotifications(vehicles){if(!globalThis.Capacitor?.isNativePlatform?.())return;await(await bridge()).plugin.configure({plan:JSON.stringify(notificationPlan(vehicles))});}
export function openNotificationSettings({getVehicle,getVehicles,open,mutate}){const v=getVehicle();open('앱 알림 설정',`<p>${esc(v.name)} · Telegram 없이 이 기기에서 알립니다.</p><p>1,000 km 또는 30일 이내에 들어오면 오전 9시대(한국시간)에 알립니다. 같은 교환 회차·단계는 중복 발송하지 않고, 기한 초과 시 다시 안내합니다.</p><p>마지막 실측 후 90일이 지나면 거리 추정 알림은 중단하고 날짜 기준은 유지합니다.</p><label class="check-option notification-check"><input id="notifications-enabled" type="checkbox" ${v.notificationEnabled?'checked':''}>이 차량 정비 알림 사용</label><button id="save-notifications" class="primary-button">알림 설정 저장</button><button id="test-notification" class="secondary-button">시험 알림 보내기</button><p id="notification-status" role="status"></p><p class="field-help">절전 정책에 따라 늦어질 수 있습니다. 앱을 강제 중지하면 다시 열 때까지 알림이 중단될 수 있습니다. 알림 계획은 앱을 열거나 기록을 저장할 때 향후 1년분을 갱신합니다. 웹 미리보기에서는 앱 내부 조회만 제공합니다.</p>`);
 document.querySelector('#save-notifications').onclick=async()=>{const status=document.querySelector('#notification-status');try{const enabled=document.querySelector('#notifications-enabled').checked;if(enabled&&globalThis.Capacitor?.isNativePlatform?.()){const result=await(await bridge()).plugin.enable();if(!result.granted){status.textContent='알림 권한이 꺼져 있습니다. 시스템 설정에서 허용해 주세요.';return;}}mutate(()=>{v.notificationEnabled=enabled;},'알림 설정을 저장했어요');status.textContent=enabled?'알림 사용으로 설정했습니다.':'이 차량 알림을 껐습니다.';}catch(e){status.textContent='설정 실패: '+e.message;}};
 document.querySelector('#test-notification').onclick=async()=>{const status=document.querySelector('#notification-status');try{if(!globalThis.Capacitor?.isNativePlatform?.()){status.textContent='설치형 Android 앱에서 시험 알림을 사용할 수 있습니다.';return;}await(await bridge()).plugin.test();status.textContent='시험 알림을 요청했습니다. 알림창을 확인해 주세요.';}catch(e){status.textContent='권한과 시스템 알림 설정을 확인해 주세요.';}};
}
