import {icon,escape as esc} from './components.js';
import {allServices,sync} from './schedule.js';
import {loadReceipt,discardReceipt,retainReceipt,getReceipt,receiptHTML} from './receipts.js';
import {createOCRReview} from './ocr-review.js';
const $=s=>document.querySelector(s);
export function createRecordEntry({getVehicle,open,forms,mileage,close,mutate}){
 let attachment=null,generation=0;
 const ocr=createOCRReview({getVehicle,open,close,mutate});
 function clearDraft(){ocr.cancel();generation++;if(attachment)discardReceipt(attachment.id);attachment=null;}
 function menu(){clearDraft();const v=getVehicle();open('기록 추가',`<div class="entry-intro"><span class="entry-car">${icon('car')}${esc(v.name)}</span></div><button class="option record-option" data-entry="camera"><span class="entry-icon">${icon('camera')}</span><span><strong>영수증 촬영</strong><small>카메라로 촬영</small></span>${icon('right','chevron')}</button><button class="option record-option" data-entry="photo"><span class="entry-icon">${icon('photo')}</span><span><strong>사진 불러오기</strong><small>저장된 영수증 선택</small></span>${icon('right','chevron')}</button><button class="option record-option" data-entry="manual"><span class="entry-icon">${icon('edit')}</span><span><strong>정비 직접 입력</strong><small>작업일·거리·비용</small></span>${icon('right','chevron')}</button><button class="option record-option" data-entry="mileage"><span class="entry-icon">${icon('trend')}</span><span><strong>주행거리만 입력</strong><small>현재 계기판 거리</small></span>${icon('right','chevron')}</button>`);
 document.querySelectorAll('[data-entry]').forEach(b=>b.onclick=()=>{if(b.dataset.entry==='manual')chooseItem();else if(b.dataset.entry==='mileage')mileage();else photo(b.dataset.entry==='camera');});
 }
 function photo(camera=false){const v=getVehicle();open(camera?'영수증 촬영':'영수증 사진 추가',`<p class="detail-vehicle">${esc(v.name)}에 첨부합니다.</p><div class="photo-drop">${icon('photo')}<h3>영수증을 선택하세요</h3><p>JPG · PNG · WebP / 최대10 MB</p><button class="primary-button" id="pick-photo">${camera?'촬영 또는 사진 선택':'사진 선택'}</button><input id="receipt-file" type="file" accept="image/jpeg,image/png,image/webp" ${camera?'capture="environment"':''} hidden></div><p id="photo-error" class="form-error" role="alert"></p><p class="field-help">인식한 내용은 확인 후 저장합니다.</p>`);
 $('#pick-photo').onclick=()=>$('#receipt-file').click();$('#receipt-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;const token=++generation;$('#photo-error').textContent='';$('#pick-photo').disabled=true;$('#pick-photo').textContent='사진을 확인하고 있어요';
 try{const r=await loadReceipt(file);if(token!==generation||!$('#sheet').open||getVehicle().id!==v.id){discardReceipt(r.id);return;}if(attachment)discardReceipt(attachment.id);attachment=r;photoReady();}
 catch(error){if(token===generation&&$('#photo-error')){$('#photo-error').textContent=error.message;$('#pick-photo').disabled=false;$('#pick-photo').textContent='다시 사진 선택';}}
 };
 }
 function photoReady(){const v=getVehicle();const duplicate=v.history.some(h=>getReceipt(h.receiptId)?.hash===attachment.hash);
 open('사진을 확인해 주세요',`<p class="detail-vehicle">${esc(v.name)} · 아직 저장하지 않았어요</p>${receiptHTML(attachment.id,true)}${duplicate?'<p class="duplicate-notice" role="status">이미 등록한 사진입니다. 중복 기록인지 확인하세요.</p>':''}<p class="field-help">사진을 읽은 뒤 날짜·거리·금액을 확인하세요.</p><button class="primary-button" id="photo-ocr">사진 글자 자동 인식</button><button class="secondary-button" id="photo-next">정비 항목 선택</button><button class="secondary-button" id="photo-reselect">다른 사진 선택</button><button class="secondary-button" id="photo-remove">사진 없이 직접 입력</button>`);
 $('#photo-ocr').onclick=()=>ocr.start(attachment,()=>{attachment=null;});$('#photo-next').onclick=chooseItem;$('#photo-reselect').onclick=()=>{clearDraft();photo();};$('#photo-remove').onclick=()=>{clearDraft();chooseItem();};
 }
 function chooseItem(){const v=getVehicle();open('무엇을 정비했나요?',`<p class="detail-vehicle">${esc(v.name)} · ${attachment?'사진을 첨부한 기록':'직접 입력'}</p>${attachment?receiptHTML(attachment.id):''}<label for="item-search">정비 항목 찾기</label><input id="item-search" placeholder="예: 엔진오일, 배터리" autocomplete="off" maxlength="60"><div id="item-options" class="item-options"></div><form id="custom-item-form" class="service-form custom-item-form"><label for="custom-item">목록에 없다면 직접 적기</label><input id="custom-item" maxlength="60" placeholder="예: 트렁크 가스리프터" autocomplete="off"><p class="field-help">교환주기는 저장 후 관리에서 설정할 수 있어요.</p><p id="item-error" class="form-error" role="alert"></p><button class="secondary-button" type="submit">이 항목으로 기록</button></form>`);
 function list(){const q=$('#item-search').value.trim().toLocaleLowerCase();const items=[...v.services,...(v.planned||[])].filter(s=>!s.deletedAt&&s.fitment!=='absent'&&s.name.toLocaleLowerCase().includes(q));$('#item-options').innerHTML=items.length?items.map(s=>`<button class="option" data-pick-item="${s.id}"><span><strong>${esc(s.name)}</strong><small>${s.fitment==='unknown'?'장착 확인 필요':s.intervalKm||s.intervalMonths?[s.intervalKm?Number(s.intervalKm).toLocaleString('ko-KR')+' km':'',s.intervalMonths?s.intervalMonths+'개월':''].filter(Boolean).join(' · '):'작업 이력 관리'}</small></span>${icon('right','chevron')}</button>`).join(''):'<p class="muted-note">일치하는 항목이 없어요. 아래에 직접 적을 수 있어요.</p>';document.querySelectorAll('[data-pick-item]').forEach(b=>b.onclick=()=>start([...v.services,...(v.planned||[])].find(s=>s.id===b.dataset.pickItem),false));}
 $('#item-search').oninput=list;list();$('#custom-item-form').onsubmit=e=>{e.preventDefault();const name=$('#custom-item').value.trim();if(!name||name.length>60){$('#item-error').textContent='항목명을 1~60자로 입력해 주세요.';return;}const existing=[...v.services,...(v.planned||[])].find(s=>s.name.toLocaleLowerCase()===name.toLocaleLowerCase());start(existing||sync({id:'custom-'+crypto.randomUUID(),name,icon:'edit',intervalKm:null,intervalMonths:null,lastKm:null,lastDate:null,referenceKm:null,referenceMonths:null,basis:'사용자가 직접 추가 · 주기 미설정'}),!existing);};
 }
 function start(s,pendingAsset){forms.record(s,undefined,{vehicleId:getVehicle().id,pendingAsset,receiptId:attachment?.id||null,onSaved:()=>{if(attachment)retainReceipt(attachment.id);attachment=null;}});}
 return {menu,onClose:clearDraft};
}
