import {readRecoveries,writeState} from './local-store.js';
import {encodeBackup,decodeBackup,exportFile} from './backup.js';
import {escape as esc} from './components.js';
export function startupImport(container){container.insertAdjacentHTML('beforeend','<h2>외부 백업으로 복구</h2><p>검사를 통과한 백업만 복구합니다. 현재 저장 데이터는 내부 이전 저장본으로 보존됩니다.</p><input id="startup-backup-file" type="file" accept=".json,application/json"><div id="startup-backup-preview"></div>');const input=container.querySelector('#startup-backup-file'),preview=container.querySelector('#startup-backup-preview');input.onchange=async()=>{try{const file=input.files[0];if(!file)return;if(file.size>50*1024*1024)throw Error('50 MB 이하만 지원합니다.');const snapshot=await decodeBackup(await file.text());preview.innerHTML=`<p>차량 ${snapshot.state.vehicles.length}대, 사진 ${snapshot.photos.length}장. 이 백업을 현재 데이터로 사용할까요?</p><button id="startup-backup-confirm">확인한 백업으로 복구</button>`;preview.querySelector('button').onclick=async()=>{input.disabled=true;preview.querySelector('button').disabled=true;try{await writeState(snapshot.state,snapshot.photos);location.reload();}catch(e){preview.textContent='복구 실패: '+e.message;input.disabled=false;}};}catch(e){preview.textContent='불러오지 않았습니다: '+e.message;}};}
export async function showRecoveries(container,setBusy=()=>{}){container.innerHTML='<p>최근 저장본 확인 중…</p>';try{const rows=await readRecoveries();container.innerHTML='<p>기록이 바뀌기 전 최근 3개 저장본입니다. 선택한 시점 전체로 되돌리며 현재 정상 저장본도 복구 목록에 남습니다. 외부 백업을 대신하지는 않습니다.</p>'+rows.map((r,i)=>`<section><strong>${esc(r.savedAt)}</strong><p>차량 ${r.state.vehicles.length}대 · 기록 ${r.state.vehicles.reduce((n,v)=>n+v.history.length,0)}건</p><button class="secondary-button" data-recovery-export="${i}">이 저장본 파일로 보관</button><button class="secondary-button" data-recovery-select="${i}">이 시점 복구 선택</button></section>`).join('')+(rows.length?'':'<p>아직 이전 저장본이 없습니다.</p>')+'<div id="recovery-confirm"></div><p id="recovery-error" role="alert"></p>';
const error=e=>container.querySelector('#recovery-error').textContent=e.message;
container.querySelectorAll('[data-recovery-export]').forEach(b=>b.onclick=async()=>{try{await exportFile(await encodeBackup(rows[+b.dataset.recoveryExport]));}catch(e){error(e);}});
container.querySelectorAll('[data-recovery-select]').forEach(b=>b.onclick=()=>{const row=rows[+b.dataset.recoverySelect],confirm=container.querySelector('#recovery-confirm');confirm.innerHTML='<p>현재 화면 대신 선택한 시점으로 돌아갑니다. 계속할까요?</p><button class="primary-button" id="recover-now">선택한 저장본으로 복구</button>';confirm.querySelector('button').onclick=async()=>{setBusy(true);try{const checked=await decodeBackup(await encodeBackup(row));await writeState(checked.state,checked.photos);location.reload();}catch(e){setBusy(false);error(e);}};});
}catch(e){container.textContent='복구 목록을 읽지 못했습니다. 자동 초기화하지 않습니다: '+e.message;}}
