import {fmt,escape as esc} from './components.js';
import {receiptHTML} from './receipts.js';
import {APP_MODE,TODAY} from './runtime.js';
import {DEMO_DATE} from './demo-data.js';
import {sync,periodText,timeline,alignedCandidate,validateRecord,commitRecord} from './schedule.js';
const optionalInt=value=>value.trim()===''?null:/^\d+$/.test(value.trim())?Number(value):NaN;
const $=s=>document.querySelector(s);
const warning='<p class="demo-warning">예시 데이터에만 반영됩니다. 새로고침하면 초기화되며 실제 차계부에는 저장하지 않습니다.</p>';
export function createServiceForms({getVehicle,open,close,mutate}){
 function editPeriod(s){const v=getVehicle();open('교환 주기 변경',`<p class="detail-vehicle">${esc(v.name)} · ${esc(s.name)}</p><dl class="detail-list"><div><dt>초기 시안 기준</dt><dd>${s.initialPeriod?periodText(s.initialPeriod):'초기 기준 미등록'}</dd></div><div><dt>현재 내 설정</dt><dd>${periodText(s)}</dd></div></dl><p class="field-help">초기 시안 기준은 제조사 공식 기준이 아닙니다.</p><form id="period-form" class="service-form"><label for="interval-km">거리 주기 (km)</label><input id="interval-km" inputmode="numeric" value="${s.intervalKm??''}" placeholder="거리 기준을 사용하지 않으면 비워두세요"><label for="interval-months">기간 주기 (개월)</label><input id="interval-months" inputmode="numeric" value="${s.intervalMonths??''}" placeholder="기간 기준을 사용하지 않으면 비워두세요"><div class="live-preview" id="period-preview" aria-live="polite"></div><p class="form-error" id="period-error" role="alert"></p>${warning}<button class="primary-button" type="submit">예시 주기 저장</button></form>`);
 const values=()=>({km:optionalInt($('#interval-km').value),months:optionalInt($('#interval-months').value)});
 const valid=({km,months})=>(km!==null||months!==null)&&(km===null||Number.isSafeInteger(km)&&km>=1&&km<=500000)&&(months===null||Number.isSafeInteger(months)&&months>=1&&months<=600);
 const next=()=>{const x=values();return valid(x)?sync({...s,intervalKm:x.km,intervalMonths:x.months,basis:'내가 수정 · 예시'}):null;};
 const update=()=>{$('#period-error').textContent='';const p=next();$('#period-preview').innerHTML=p?`<strong>변경 후 ${periodText(p)}</strong>${p.target!==undefined?'거리 목표 '+fmt(p.target)+' km<br>':''}${p.date?'날짜 목표 '+p.date.replaceAll('-','. ')+'<br>':''}${p.target===undefined&&!p.date?'마지막 교환 기록을 남기면 다음 시점을 계산해요.':'실제 교환 기록은 바꾸지 않아요.'}${p.referenceKm||p.referenceMonths?'<p class="reference-warning">더 이른 참고 기한은 계속 적용합니다.</p>':''}`:'거리(1~500,000 km) 또는 기간(1~600개월)을 입력하세요.';};
 $('#period-form').addEventListener('input',update);update();
 $('#period-form').onsubmit=e=>{e.preventDefault();const p=next();if(!p){$('#period-error').textContent='거리 또는 기간 중 하나 이상을 올바르게 입력해 주세요.';return;}mutate(()=>{const previous={km:s.intervalKm,months:s.intervalMonths};Object.assign(s,p);s.userPeriodChanged=true;s.ruleHistory=[...(s.ruleHistory||[]),{previous,next:values(),at:DEMO_DATE}];},'예시 정비 주기를 변경했어요');close();};
 }
 function record(s,draft,context={}){const v=getVehicle();const today=APP_MODE?TODAY():DEMO_DATE;const d=draft||{date:context.receiptId?'':today,km:null,cost:null,action:'replace',aligned:false,companions:[]};
 open('정비 기록하기',`<p class="detail-vehicle">${esc(v.name)} · ${esc(s.name)}</p>${receiptHTML(context.receiptId)}<form id="service-form" class="service-form"><label for="service-date">실제 작업일</label><input id="service-date" type="date" max="${today}" value="${esc(d.date)}"><label for="service-action">작업 종류</label><select id="service-action">${[['replace','교환'],['inspect','점검'],['clean','청소'],['refill','보충'],['adjust','조정·위치교환'],['lubricate','윤활'],['other','수리·기타']].map(([a,l])=>`<option value="${a}" ${d.action===a?'selected':''}>${l}</option>`).join('')}</select><label for="service-km">작업 당시 실제 주행거리 (km)</label><input id="service-km" inputmode="numeric" value="${d.km??''}" placeholder="계기판에서 확인한 거리를 입력하세요"><p class="field-help">예상 주행거리를 실제 기록으로 자동 입력하지 않아요.</p>${s.clockOrigin==='manufactured'?`<label>교환한 부품 제조일<input type="date" id="service-manufacture" max="${today}" value="${d.manufactureDate||''}"></label>`:''}<label for="service-cost">이번 작업 총비용 (원 · 선택)</label><input id="service-cost" inputmode="numeric" value="${d.cost??''}" placeholder="모르면 비워두세요"><p class="field-help">동반 부품을 포함한 총비용을 한 번만 입력해요.</p><label class="check-option"><input id="align-slot" type="checkbox" ${d.aligned?'checked':''}><span id="align-label">가까운 정비회차에 맞춤</span></label><div id="record-preview" class="live-preview" aria-live="polite"></div>${s.companions?.length?`<details class="detail-fold" open><summary>실제로 함께 교환한 항목</summary>${s.companions.map(c=>`<label class="check-option"><input type="checkbox" data-companion="${c.id}" ${d.companions.includes(c.id)?'checked':''}><span>${esc(c.name)}<br><small>${esc(c.reason)}</small></span></label>`).join('')}</details>`:''}<details class="detail-fold"><summary>정비소·메모 추가 (선택)</summary><label for="service-shop">정비소</label><input id="service-shop" maxlength="120" value="${esc(d.shop||'')}"><label for="service-memo">메모</label><textarea id="service-memo" maxlength="1000" rows="3">${esc(d.memo||'')}</textarea></details><p id="record-error" class="form-error" role="alert"></p>${warning}<button class="primary-button" type="submit">내용 확인</button></form>`);
 const values=()=>({manufactureDate:$('#service-manufacture')?.value||null,shop:$('#service-shop').value.trim(),memo:$('#service-memo').value.trim(),date:$('#service-date').value,km:$('#service-km').value.trim()===''?NaN:optionalInt($('#service-km').value),cost:optionalInt($('#service-cost').value),action:$('#service-action').value,aligned:$('#align-slot').checked,companions:[...document.querySelectorAll('[data-companion]:checked')].map(el=>el.dataset.companion)});
 const update=()=>{$('#record-error').textContent='';const r=values(),canReplace=r.action==='replace',slot=Number.isSafeInteger(r.km)?alignedCandidate(r.km,s.intervalKm):null;$('#align-slot').disabled=!canReplace||slot===null;if($('#align-slot').disabled)$('#align-slot').checked=false;$('#align-label').textContent=slot!==null?`${fmt(slot)} km 회차에 맞춤 (직접 선택)`:'가까운 회차가 있을 때 선택할 수 있어요';
 document.querySelectorAll('[data-companion]').forEach(el=>{el.disabled=!canReplace;if(!canReplace)el.checked=false;});
 const current=values();const error=validateRecord(v,s,current);if(!canReplace){$('#record-preview').textContent='점검·청소·보충은 교환 주기를 초기화하지 않아요.';return;}if(error){$('#record-preview').textContent='실제 날짜와 거리를 입력하면 다음 목표를 미리 보여드려요.';return;}
 if(s.lastDate&&current.date<s.lastDate){$('#record-preview').textContent='과거 이력으로 저장하며 더 최근의 교환 기준은 유지해요.';return;}
 const p=sync({...s,manufactureDate:current.manufactureDate||s.manufactureDate,lastDate:current.date,lastKm:current.km,basisKm:current.aligned?slot:current.km});const t=timeline(v,p);$('#record-preview').innerHTML=`<strong>저장 후 다음 목표</strong>${p.target!==undefined?fmt(p.target)+' km<br>':''}${p.date?p.date.replaceAll('-','. ')+'<br>':''}${!p.date&&p.target===undefined?'교환 기록만 저장해요. 주기는 별도로 설정할 수 있어요.':''}${t.sourceKm&&t.sourceKm<p.target?`<p class="reference-warning">참고 기한 ${fmt(t.sourceKm)} km를 먼저 안내해요.</p>`:''}`;};
 $('#service-form').addEventListener('input',update);$('#service-form').addEventListener('change',update);update();
 $('#service-form').onsubmit=e=>{e.preventDefault();const r=values(),error=validateRecord(v,s,r);if(error){$('#record-error').textContent=error;return;}review(s,r,context);};
 }
 function review(s,d,context){const v=getVehicle(),labels={replace:'교환',inspect:'점검',clean:'청소',refill:'보충',adjust:'조정·위치교환',lubricate:'윤활',other:'수리·기타'};const selected=(s.companions||[]).filter(c=>d.companions.includes(c.id));open('이 내용으로 기록할까요?',`<p class="detail-vehicle">${esc(v.name)}</p><dl class="detail-list"><div><dt>항목</dt><dd>${esc([s.name,...selected.map(c=>c.name)].join(' · '))}</dd></div><div><dt>작업</dt><dd>${labels[d.action]}</dd></div><div><dt>실제 작업일</dt><dd>${d.date}</dd></div><div><dt>실제 주행거리</dt><dd>${fmt(d.km)} km</dd></div><div><dt>계산 기준</dt><dd>${d.aligned?fmt(alignedCandidate(d.km,s.intervalKm))+' km 회차':'실제 거리'}</dd></div><div><dt>총비용</dt><dd>${d.cost===null?'미입력':fmt(d.cost)+'원'}</dd></div></dl>${d.shop?`<p class="record-note">정비소: ${esc(d.shop)}</p>`:''}${d.memo?`<p class="record-note">${esc(d.memo)}</p>`:''}${receiptHTML(context.receiptId)}${warning}<button class="primary-button" id="confirm-record">예시 기록 저장</button><button class="secondary-button" id="back-record">돌아가서 수정</button>`);
 $('#back-record').onclick=()=>record(s,d,context);$('#confirm-record').onclick=()=>{const error=validateRecord(v,s,d);if(error||context.vehicleId&&getVehicle().id!==context.vehicleId)return;$('#confirm-record').disabled=true;mutate(()=>{if(context.pendingAsset)(v.planned??=[]).push(s);const entry=commitRecord(v,s,d);if(context.receiptId)entry.receiptId=context.receiptId;context.onSaved?.();},'예시 정비 기록을 저장했어요');close();};
 }
 return {editPeriod,record};
}
