import {catalog} from './catalog-data.js';
import {fitment} from './catalog-link.js';
import {escape as esc,fmt} from './components.js';
import {conditionOptions,vehicleFromFields} from './vehicle-model.js';
import {parseLog} from './log-import.js';
export function createVehicleView({open,close,getVehicle,getVehicles,add,mutate}){
 function form(edit=false){const current=edit?getVehicle():null;let imported=null;
  open(edit?'차량 조건 변경':'차량 등록',`<form id="vehicle-register" class="service-form"><label for="registration-name">차량 이름</label><input id="registration-name" maxlength="60" value="${esc(current?.name||'')}" required placeholder="예: 우리집 SUV">${Object.entries(conditionOptions).map(([key,options])=>`<label for="registration-${key}">${{fuel:'동력·연료',drive:'구동 방식',transmission:'변속기 구조',battery:'12 V 배터리 종류'}[key]}</label><select id="registration-${key}">${options.map(([value,label])=>`<option value="${value}" ${value===(current?.conditions?.[key]||'unknown')?'selected':''}>${label}</option>`).join('')}</select>`).join('')}<label for="registration-mode">관리 범위</label><select id="registration-mode"><option value="all">전체 관리 · 네 묶음 모두</option><option value="basic" ${current?.managementMode==='basic'?'selected':''}>기본 관리</option></select><p class="field-help">모르는 사양은 모름으로 두세요. 전체 관리도 미장착 부품까지 교환하라는 뜻은 아닙니다. 등록 후 관리 화면에서 전체 항목과 과거 기록을 연결할 수 있습니다.</p>${edit?'':'<label for="vehicle-log-file">기존 텍스트 차계부 (선택 · UTF-8)</label><input id="vehicle-log-file" type="file" accept=".txt,text/plain"><div id="log-preview" class="field-help"></div>'}<p class="form-error" id="registration-error" role="alert"></p><button id="save-vehicle" class="primary-button" type="submit">${edit?'차량 조건 저장':'차량 등록'}</button></form>`);
  const input=document.querySelector('#vehicle-log-file'),save=document.querySelector('#save-vehicle'),error=document.querySelector('#registration-error');
  if(input)input.onchange=async()=>{imported=null;save.disabled=true;error.textContent='';try{const file=input.files[0];if(!file)return;if(file.size>1024*1024)throw Error('1 MB 이하만 지원합니다.');imported=await parseLog(await file.text(),file.name);document.querySelector('#log-preview').textContent=`정비 방문 ${imported.history.length}건 · 날짜 확인 필요 ${imported.pendingRecords.length}건 · 원문 전체 보존. 비용은 미입력으로 두고 교환주기는 자동 설정하지 않습니다.`;}catch(e){error.textContent=e.message;}finally{save.disabled=false;}};
  document.querySelector('#vehicle-register').onsubmit=e=>{e.preventDefault();try{if(input?.files.length&&!imported)throw Error('차계부를 읽지 못했습니다. 파일을 다시 선택해 주세요.');const fields=Object.fromEntries(['name','fuel','drive','transmission','battery','mode'].map(key=>[key,document.querySelector('#registration-'+key).value]));const v=vehicleFromFields(fields);
   if(edit){mutate(()=>{Object.assign(current,{name:v.name,meta:v.meta,conditions:v.conditions,managementMode:v.managementMode,managePacks:v.managePacks});for(const s of current.services){const row=catalog.find(r=>r.id===s.id);if(row&&!s.fitmentConfirmedByUser&&!s.lastDate)s.fitment=fitment(current,row);}},'차량 조건을 저장했어요');close();return;}
   if(imported){if(getVehicles().some(x=>x.sourceHash===imported.sourceHash))throw Error('이미 등록한 차계부입니다. 중복으로 가져오지 않았어요.');if(imported.details.vin&&getVehicles().some(x=>x.details?.vin===imported.details.vin))throw Error('같은 차대번호의 차량이 이미 있습니다. 기존 차량을 확인해 주세요.');Object.assign(v,imported);}add(v);close();
  }catch(e){error.textContent=e.message;}};
 }
 function source(){const v=getVehicle(),doc=v.sourceDocument;open('가져온 차계부 원문',`<p>원문은 수정하지 않고 보관합니다. 부품 규격·용량·토크는 사용자 메모이며 검증된 정비 지침이 아닙니다.</p>${(v.pendingRecords||[]).map(h=>`<section><h3>${h.resolvedRecordId?'날짜 확인 완료 · 원문 보존':'날짜 확인 필요'} · ${fmt(h.km)} km</h3><pre class="source-log">${esc(h.memo)}</pre></section>`).join('')}${doc?.warnings?.length?`<h3>확인할 내용</h3>${doc.warnings.map(w=>`<p>${esc(w)}</p>`).join('')}`:''}<h3>${esc(doc?.filename||'원문 없음')}</h3><pre class="source-log">${esc(doc?.text||'가져온 텍스트가 없습니다.')}</pre>`);}
 return {form,source};
}
