const assert=require('node:assert/strict'),path=require('node:path');
const {chromium}=require(process.env.VEHICLE_PLAYWRIGHT_PATH||'playwright');
(async()=>{const browser=await chromium.launch({headless:true});try{const p=await browser.newPage({viewport:{width:390,height:844}}),errors=[],external=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith('http://127.0.0.1:4178/'))external.push(r.url());});
const fixture=await browser.newPage();await fixture.setContent('<body style="background:white;padding:30px;font:24px sans-serif"><h1>가상 영수증</h1><p>UI 테스트 전용</p><p>2026-09-06 / 148200 km</p><p>테스트 부품 / 25000원</p></body>');const buffer=await fixture.screenshot();await fixture.close();
await p.goto('http://127.0.0.1:4178/');const add=()=>p.locator('.bottom-nav [data-page="add"]').click();const custom=async name=>{await p.locator('#custom-item').fill(name);await p.getByRole('button',{name:'이 항목으로 기록',exact:true}).click();};
await add();await p.screenshot({path:path.join(__dirname,'evidence/entry-390.png')});await p.locator('[data-entry="manual"]').click();await custom('취소한 부품');await p.keyboard.press('Escape');await add();await p.locator('[data-entry="manual"]').click();assert.equal(await p.locator('[data-pick-item]').count(),4);await p.locator('#item-search').fill('엔진');assert.equal(await p.locator('[data-pick-item]').count(),1);await p.keyboard.press('Escape');
await add();await p.locator('[data-entry="photo"]').click();await p.locator('#receipt-file').setInputFiles({name:'bad.txt',mimeType:'text/plain',buffer:Buffer.from('test')});await p.waitForFunction(()=>document.querySelector('#photo-error').textContent.length>0);
await p.locator('#receipt-file').setInputFiles({name:'test.png',mimeType:'image/png',buffer});await p.locator('#photo-next').waitFor();await p.screenshot({path:path.join(__dirname,'evidence/receipt-390.png')});await p.locator('#photo-next').click();const name='<img src=x onerror=alert(1)>';await custom(name);assert.equal(await p.locator('#service-date').inputValue(),'');assert.equal(await p.locator('#service-km').inputValue(),'');assert.equal(await p.locator('#service-cost').inputValue(),'');await p.locator('#service-date').fill('2026-09-06');await p.locator('#service-km').fill('148200');await p.locator('#service-cost').fill('25000');await p.getByText('정비소·메모 추가 (선택)',{exact:true}).click();await p.locator('#service-shop').fill('가상 정비소');await p.locator('#service-memo').fill('<script>alert(1)</script>');await p.getByRole('button',{name:'내용 확인',exact:true}).click();assert.equal(await p.locator('#sheet-body script').count(),0);await p.locator('#back-record').click();assert.equal(await p.locator('#service-memo').inputValue(),'<script>alert(1)</script>');await p.getByRole('button',{name:'내용 확인',exact:true}).click();await p.locator('#confirm-record').click();await p.locator('.bottom-nav [data-page="history"]').click();await p.locator('[data-history="0"]').click();assert.ok((await p.locator('dialog').innerText()).includes(name));assert.equal(await p.locator('.receipt-preview').count(),1);await p.locator('.receipt-preview summary').click();assert.equal(await p.locator('.receipt-preview img').evaluate(el=>el.complete&&el.naturalWidth>0),true);await p.keyboard.press('Escape');
await add();await p.locator('[data-entry="photo"]').click();await p.locator('#receipt-file').setInputFiles({name:'same.png',mimeType:'image/png',buffer});await p.locator('.duplicate-notice').waitFor();await p.locator('#photo-remove').click();assert.equal(await p.locator('.receipt-preview').count(),0);await p.keyboard.press('Escape');
for(const width of [360,390,430,1280]){await p.setViewportSize({width,height:844});await add();assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.locator('[data-entry="manual"]').click();await custom('추가 테스트');await p.locator('#service-km').fill('148200');await p.getByRole('button',{name:'내용 확인',exact:true}).click();await p.locator('#back-record').click();await p.keyboard.press('Escape');}
await p.setViewportSize({width:390,height:844});await p.addStyleTag({content:'html{font-size:200%}'});await add();await p.locator('[data-entry="manual"]').click();await custom('큰 글자 테스트');await p.locator('#service-km').fill('148200');await p.getByRole('button',{name:'내용 확인',exact:true}).click();await p.screenshot({path:path.join(__dirname,'evidence/entry-large-text.png')});await p.keyboard.press('Escape');await p.reload();await add();await p.locator('[data-entry="manual"]').click();assert.equal(await p.locator('[data-pick-item]').count(),4);assert.deepEqual(errors,[]);assert.deepEqual(external,[]);console.log('PASS: entry, cancel, search, custom item, literal text, photo preview/save/duplicate/remove, reset, responsive flows, no external requests');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
