const assert=require('node:assert/strict'),path=require('node:path');
const {chromium}=require(process.env.VEHICLE_PLAYWRIGHT_PATH||'playwright');
(async()=>{const b=await chromium.launch({headless:true});try{
 const p=await b.newPage({viewport:{width:390,height:844}}),errors=[],external=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith('http://127.0.0.1:4178/'))external.push(r.url());});
 await p.goto('http://127.0.0.1:4178/');assert.ok(await p.locator('.bottom-nav').isVisible());
 const f=await b.newPage({viewport:{width:1200,height:900}});await f.setContent('<body style="margin:0;padding:50px;background:white;color:black;font:32px Arial, sans-serif;line-height:1.8"><h2>자동차 정비명세서 - 가상 시험용</h2><p>정비완료일 2026-09-06<br>주행거리 148,200 km<br>엔진오일 교환<br>오일필터 교환<br>총액 100,000<br>업체명: 가상 정비소</p></body>');const buffer=await f.screenshot();await f.close();
 await p.locator('.bottom-nav [data-page="add"]').click();await p.locator('[data-entry="photo"]').click();await p.locator('#receipt-file').setInputFiles({name:'synthetic-statement.png',mimeType:'image/png',buffer});await p.locator('#photo-ocr').click();
 await p.locator('#ocr-form').waitFor({timeout:90000});await p.screenshot({path:path.join(__dirname,'evidence/ocr-390.png')});
 const detectedDate=await p.locator('#ocr-date').inputValue();assert.ok(['','2026-09-06'].includes(detectedDate));console.log('OCR date:',detectedDate||'uncertain; user correction required');await p.locator('#ocr-date').fill('2026-09-06');
 assert.equal(await p.locator('#ocr-date').inputValue(),'2026-09-06');assert.equal(await p.locator('#ocr-km').inputValue(),'148200');assert.equal(await p.locator('#ocr-cost').inputValue(),'100000');assert.ok(await p.locator('.ocr-item').count()>=2);assert.equal(await p.locator('[data-use]:checked').count(),0);
 await p.locator('[data-use]').nth(0).check();await p.locator('[data-use]').nth(1).check();await p.locator('[data-action]').nth(0).selectOption('replace');await p.locator('[data-action]').nth(1).selectOption('replace');
 await p.getByRole('button',{name:'선택한 내용 확인',exact:true}).click();await p.locator('#ocr-back').click();assert.equal(await p.locator('[data-use]:checked').count(),2);await p.getByRole('button',{name:'선택한 내용 확인',exact:true}).click();await p.locator('#ocr-save').click();await p.locator('.bottom-nav [data-page="history"]').click();assert.equal(await p.locator('.history-row').count(),3);
 await p.locator('.bottom-nav [data-page="home"]').click();assert.ok((await p.locator('.spend-card').innerText()).includes('720,000'));await p.locator('[data-undo]').click();assert.ok((await p.locator('.spend-card').innerText()).includes('620,000'));
 for(const [label,html] of [['general','<h2>자동차 정비명세서</h2><p>작업일 2026-09-06</p><p>주행거리 148,200 km</p><table border="1" cellpadding="20"><tr><td>작업내용</td><td>부품</td><td>공임</td></tr><tr><td>엔진오일 교환</td><td>50,000</td><td>20,000</td></tr></table><p>총액 70,000</p>'],['payment','<h2>카드 매출전표</h2><p>결제일 2026-09-06</p><p>합계 금액 70,000</p><p>승인번호 12345678</p>']]){
 const fixture=await b.newPage({viewport:{width:1100,height:850}});await fixture.setContent('<body style="background:white;color:black;padding:40px;font:32px Arial,sans-serif">'+html+'</body>');const png=await fixture.screenshot();await fixture.close();
 const result=await p.evaluate(async uri=>{const {recognizeReceipt}=await import('/ocr-engine.js');const {parseReceipt}=await import('/receipt-parser.js');const text=await recognizeReceipt(uri).promise;return {length:text.length,parsed:parseReceipt(text)};},'data:image/png;base64,'+png.toString('base64'));assert.ok(result.length>25);if(label==='payment'){assert.equal(result.parsed.date,'');assert.equal(result.parsed.km,null);assert.equal(result.parsed.items.length,0);}console.log('PASS: real OCR synthetic '+label+' document');
 }
 await p.locator('.bottom-nav [data-page="add"]').click();await p.locator('[data-entry="photo"]').click();await p.locator('#receipt-file').setInputFiles({name:'cancel.png',mimeType:'image/png',buffer});await p.locator('#photo-ocr').click();await p.locator('#ocr-cancel').click();assert.equal(await p.locator('dialog[open]').count(),0);
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);console.log('PASS: real Korean image OCR, date confirmation, extracted km/total, explicit multiple-item save, cost counted once, undo, no external requests');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
