const assert=require('node:assert/strict'),path=require('node:path');
const {chromium}=require(process.env.VEHICLE_PLAYWRIGHT_PATH||'playwright');
(async()=>{const b=await chromium.launch({headless:true});try{const p=await b.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:4178/');const nav=id=>p.locator('.bottom-nav [data-page="'+id+'"]').click();await nav('manage');assert.equal(await p.locator('[data-pack]').count(),4);await p.screenshot({path:path.join(__dirname,'evidence/manage-390.png')});
await p.locator('[data-pack="basic"]').click();assert.ok((await p.locator('dialog').innerText()).includes('엔진오일'));await p.locator('#apply-pack').click();assert.equal(await p.locator('.manage-group').count(),3);await nav('upcoming');assert.equal(await p.locator('.upcoming-card').count(),4);await nav('history');assert.equal(await p.locator('.visit-card').count(),2);await nav('manage');await p.locator('[data-undo]').click();assert.equal(await p.locator('.manage-group').count(),4);
await p.locator('[data-pack="basic"]').click();await p.locator('dialog [data-edit-period="oil"]').click();assert.ok((await p.locator('dialog').innerText()).includes('초기 시안 기준'));await p.locator('#interval-km').fill('5000');await p.getByRole('button',{name:'예시 주기 저장',exact:true}).click();await p.locator('[data-pack="basic"]').click();await p.locator('dialog [data-edit-period="oil"]').click();assert.ok((await p.locator('.detail-list').innerText()).includes('10,000'));assert.equal(await p.locator('#interval-km').inputValue(),'5000');await p.keyboard.press('Escape');await p.locator('[data-undo]').click();
await p.locator('[data-manage-info]').click();await p.locator('#vehicle-plate').fill('가상 번호판');await p.locator('#vehicle-vin').fill('TESTONLY1234567890');await p.locator('#vehicle-note').fill('<script>가상 메모</script>');await p.getByRole('button',{name:'예시 차량 정보 저장',exact:true}).click();await nav('home');assert.ok(!(await p.locator('#main').innerText()).includes('가상 번호판'));await nav('manage');await p.locator('[data-manage-info]').click();assert.equal(await p.locator('#vehicle-note').inputValue(),'<script>가상 메모</script>');assert.equal(await p.locator('#sheet-body script').count(),0);await p.keyboard.press('Escape');await p.locator('[data-undo]').click();await p.locator('[data-manage-info]').click();assert.equal(await p.locator('#vehicle-plate').inputValue(),'');await p.keyboard.press('Escape');
await p.locator('[data-manage-alert]').click();assert.ok((await p.locator('dialog').innerText()).includes('알림을 발송하지 않습니다'));await p.keyboard.press('Escape');
await p.locator('#vehicle-picker').click();await p.locator('[data-vehicle="new"]').click();await p.locator('[data-pack="major"]').click();assert.ok((await p.locator('dialog').innerText()).includes('등록된 항목이 없어요'));await p.keyboard.press('Escape');
for(const width of [360,430,768,1280]){await p.setViewportSize({width,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.locator('[data-pack="long"]').click();await p.keyboard.press('Escape');}
await p.setViewportSize({width:390,height:844});await p.addStyleTag({content:'html{font-size:200%}'});await p.screenshot({path:path.join(__dirname,'evidence/manage-large-text.png')});await p.locator('[data-manage-info]').click();await p.locator('#vehicle-note').fill('큰 글자 시험');await p.getByRole('button',{name:'예시 차량 정보 저장',exact:true}).click();await p.reload();await nav('manage');await p.locator('[data-manage-info]').click();assert.equal(await p.locator('#vehicle-note').inputValue(),'');assert.deepEqual(errors,[]);console.log('PASS: packs preview/hide/undo without lost history/schedules, initial/current period, vehicle details privacy/undo, notification boundary, empty vehicle, responsive flows, reload reset');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
